### ISSUE TITLE
Object type names

### ISSUE THREAD

**Issue by eneserdo** [zubair-irshad/CenterSnap#2]
Thank you for the great work. I checked the code and the notebook, but I could not figure out how to access and print the object's label name. Could you help me with that?

**Comment by zubair-irshad** [comment]
Thanks @eneserdo for your question. We are going to release the code in a couple of days. In the released codebase, the following information can help you retrieve the correct object names:


These are GT object key to names used by the NOCS code base to evaluate the GT RTs with the predicted RTs. 
```
object_key_to_name= {0: 'background', 1:'bottle', 2:'bowl', 3:'camera', 4:'can', 5:'laptop', 6:'mug'}
```

Shapenet ID to name (only needed for collecting your own data or retrieving objects from shapenet reposiotry):
```
id_to_name = {'02876657':'bottle','02880940': 'bowl','02942699':'camera','02946921':'can',,'03642806':'laptop','03797390':'mug'}
```
