### ISSUE TITLE
custom data

### ISSUE THREAD

**Issue by peng25zhang** [zubair-irshad/CenterSnap#23]
@zubair-irshad  Hi, sorry to bother you, I want to generate custom data, and I donot know how to cal scale_factors? (*norm.txt), please help

**Comment by zubair-irshad** [comment]
Hi @peng25zhang, 

Can you say more about your data specs? You don't need *norm.txt file for a synthetic dataset but you need it for real dataset. [This](https://github.com/zubair-irshad/CenterSnap/blob/88f874b79e146dddf6b1b63f7576571ddb378520/prepare_data/generate_data_nocs.py#L266) is how we load scale factors from `norm.txt` and [this](https://github.com/zubair-irshad/CenterSnap/blob/88f874b79e146dddf6b1b63f7576571ddb378520/prepare_data/generate_data_nocs.py#L297), [this](https://github.com/zubair-irshad/CenterSnap/blob/88f874b79e146dddf6b1b63f7576571ddb378520/prepare_data/generate_data_nocs.py#L301) and [this](https://github.com/zubair-irshad/CenterSnap/blob/88f874b79e146dddf6b1b63f7576571ddb378520/prepare_data/generate_data_nocs.py#L316) is how we eventually save it in our CenterSnap format to be later used for regression.

Note that we did not create the NOCS data ourself and merely use the data [NOCS](https://github.com/hughw19/NOCS_CVPR2019) provided to process data in the correct format required by CenterSnap. We need norm.txt to calculate the sizes (i.e. W,H,L dimensions) of the canonical bounding box of each shape which we later regress along with R,T in CenterSnap model. One can get this size information if you have mesh/pointcloud available for that shape by normalizing the meshes/pointclouds of all instances within a category to fit in a unit bounding box and calculating scale as np.min and np.max for x,y and z dimensions. 

Hope it helps!

**Comment by peng25zhang** [comment]
@zubair-irshad Thank you very much for your reply. Now I know generating custom data does not require NOCS map.  But  I can not access the link of 'model_50_nocspth' for preprocessing my data. Can I access it on another site(not www.Dropbox)
