### ISSUE TITLE
Setting train_path and val_path in net_config.txt

### ISSUE THREAD

**Issue by ChaejungMaeng** [zubair-irshad/CenterSnap#3]
Hello, 

Is it possible to make the dataset through the below train and val paths when running net_train.py?
or Do you have a plan to release the dataset later?

--train_path=s3://mmt-learning-data/simnet/output/zubair_panoptic_NOCS_CAM_train_complete
--val_path=s3://mmt-learning-data/simnet/output/zubair_panoptic_NOCS_Real_val_complete

I was just curious if there is a way to make the required dataset by myself or if it is blocked from downloading through those paths. 

Thank you.

**Comment by zubair-irshad** [comment]
Thanks for your interest in our work. We will be releasing thw dataset (in the format required to train our network) as part of our official code release close to the ICRA conference date.

**Comment by zubair-irshad** [comment]
Hi @ChaejungMaeng, we have officially released our code and preprocessed dataset here: https://github.com/zubair-irshad/CenterSnap
